name: CI

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install dependencies
        run: sudo apt-get install sqlite3 libsqlite3-dev
      - name: Install bundler
        run: gem install bundler
      - name: Install gems
        run: bundle install --jobs 4 --retry 3
      - name: Prepare DB
        env:
          RAILS_ENV: test
        run: bundle exec rake db:setup
      - name: Run Tests
        run: bundle exec rspec
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install rubocop
        run: gem install rubocop -v 1.25.0
      - name: Install rubocop-rspec
        run: gem install rubocop-rspec -v 1.36.0
      - name: Run rubocop
        run: rubocop
